### ISSUE TITLE
Add phase animation to package

### ISSUE THREAD

**Issue by andydandy74** [BadMonkeysInc/Dynanimator#5]
I just added the capability to animate phases - 349e9806bd99bcfc5713bd19e791d2f2190e4091
It relies on some new nodes I made for package Clockwork that list the phases chronologically and allow changing a view's phase. 
@vasshaug - I'll let you know when the new Clockwork version is out so we don't have dependency issues.

**Comment by andydandy74** [comment]
@vasshaug - Just published Clockwork 0.75.23 that includes all the nodes needed for accessing phases.

**Comment by vasshaug** [comment]
Just published new version including Clockwork 0.75.23. Want to check if ok @andydandy74 ?

**Comment by andydandy74** [comment]
@vasshaug - somehow not quite okay. ;-)
Missing the Phase nodes.
Can you copy all nodes from the repo (folder Dynanimator/nodes), paste them to C:\Users\USERNAME\AppData\Roaming\Dynamo\0.7\packages\Dynanimator\dyf and upload another version.

**Comment by andydandy74** [comment]
@vasshaug - Also, please download latest version of Clockwork (0.75.24) again before publishing the next version... ;-)

**Comment by vasshaug** [comment]
Thanks for holding my hand @andydandy74 It should be updated and okay now.

**Comment by andydandy74** [comment]
LOL - I'll hold your time any time you want :-D
