### ISSUE TITLE
Suggestion: Restructure project

### ISSUE THREAD

**Issue by redinkinc** [BadMonkeysInc/Dynanimator#9]
Hi,
I would suggest following changes:
name folders "nodes" to "dyf" and "samples" to "extra" to fit the Dynamo Package convention.
Move "wiki_imgs" either to Dynanimato.wiki (if intended to use it in the wiki) or "extra" (if intended to use them in the package).

**Comment by andydandy74** [comment]
This has been addressed in 2db18137cb9074901e8fadf53c7c2ad5f559f2eb and c694e23af3317084e5e987d4aa45b31a1a91dfa4
Everything that is supposed to end up in the actual package is now organized in the folder aptly named `package`
